# https://docs.docker.com/go/compose-spec-reference/

# https://github.com/docker/awesome-compose
services:
  server:
    build:
      context: ../
      dockerfile: docker/dev.Dockerfile
    ports:
      - 8080:8080
    env_file:
      - path: ../.env
        required: true
    depends_on:
      db:
        condition: service_healthy
  db:
    image: preloaded-db
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=bojong_ireng
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 3
volumes:
  db-data:
secrets:
  db-password:
    file: "./db/password.txt"

